import datetime
 
log_file_path = r"C:\Users\cbhattacha015\OneDrive - PwC\Downloads\AEM Learning\Author\crx-quickstart\logs\error.log"
 
today_date_str = datetime.datetime.now().strftime("%d.%m.%Y")
 
unregistering_list = []
stopped_list = []
started_list = []
event_started_list = []
event_stopped_list = []
bundle_set = set()
bundle_started_set = set()
bundle_stopped_set = set()
bundle_starting_set = set()
bundle_stopping_set = set()
bundle_resolved_set = set()


with open(log_file_path, "r") as log_file:
    for line in log_file:
        if line.startswith(today_date_str):
            lower_line = line.lower()
            if "unregistering" in lower_line and "impl." in  lower_line :
                unregistering_list.append(line.strip())
            if "stopped" in lower_line and "impl." in  lower_line:
                stopped_list.append(line.strip())
            if "started" in lower_line and "impl." in  lower_line:
                started_list.append(line.strip())
            if "event started" in lower_line:
                event_started_list.append(line.strip())
            if "event stopped" in lower_line:
                event_stopped_list.append(line.strip())
            if "bundleevent" in lower_line:
                x=line.strip().split(" ")[4]
                bundle_set.add(x)
                y=lower_line.strip().split(" ")[-1]
                if "started" in y:
                    bundle_started_set.add(x)
                if "stopped" in y:
                    bundle_stopped_set.add(x)
                if "starting" in y:
                    bundle_starting_set.add(x)
                if "stopping" in y:
                    bundle_stopping_set.add(x)
                if "resolved" in y:
                    bundle_resolved_set.add(x)
                if x not in bundle_started_set and x not in bundle_stopped_set and x not in bundle_starting_set and x not in bundle_stopping_set and x not in bundle_resolved_set:
                    print(line)

                
            
  
print(f"\n\nLength of UNREGISTERING = {len(unregistering_list)}\n\n\nLength of STOPPED = {len(stopped_list)}\n\n\nLength of STARTED = {len(started_list)}")
print(f"\n\nLength of EVENT STOPPED = {len(event_stopped_list)}\n\n\nLength of EVENT STARTED = {len(event_started_list)}")
print(f'''
      \n\nLength of BUNDLE EVENT SET = {len(bundle_set)}
      \n\nLength of BUNDLE EVENT STARTING SET = {len(bundle_starting_set)}
      \n\nLength of BUNDLE EVENT STARTED SET = {len(bundle_started_set)}
      \n\nLength of BUNDLE EVENT STOPPED SET = {len(bundle_stopped_set)}
      \n\nLength of BUNDLE EVENT STOPPING SET = {len(bundle_stopping_set)}
      \n\nLength of BUNDLE EVENT RESOLVED SET = {len(bundle_resolved_set)}
''')


print("\n\nBundles in started and not in stopping:")
for x in bundle_started_set:
    if x not in bundle_stopping_set:
        print(x)


print("\n\nBundles in stopped and not in starting:")
for x in bundle_stopped_set:
    if x not in bundle_starting_set:
        print(x)

print("\n\nBundles in resolved and not in started or stopped:")
for x in bundle_resolved_set:
    if x not in bundle_started_set and x not in bundle_stopped_set:
        print(x)


print("\n\nBundles in started and not in stopped:")
for x in bundle_started_set:
    if x not in bundle_stopped_set:
        print(x)


trimmed_stopped = []
for ev in event_stopped_list:
    trimmed_stopped.append(" ".join(ev.split(" ")[2:-1]))

print("\n\nEvents which STARTED and NOT STOPPED:")
trimmed_started = []
for ev in event_started_list:
    x=" ".join(ev.split(" ")[2:-1])
    trimmed_started.append(x)
    if x not in trimmed_stopped:
        print(ev)

#print(len(bundle_list))

unregistering_list2 = []
stopped_list2 = []
with open(log_file_path, "r") as log_file:
    for line in log_file:
        if line.startswith(today_date_str):
            lower_line = line.lower()
            if "unregistering" in lower_line :
                unregistering_list2.append(line.strip())
            if "stopped" in lower_line and "event stopped" not in lower_line:
                stopped_list2.append(line.strip())

#print(f"\n\nLength of UNREGISTERING ONLY LIST = {len(unregistering_list2)}")
#print(f"\n\nLength of STOPPED and NOT EVENT STOPPED = {len(stopped_list2)}")
print("\n\n")

""" print("\n\n\nBUNDLE EVENTS ONLY STARTED")
for ev in bundle_started_set:
    if ev not in bundle_stopped_set:
        print(ev)

print("\n\n\nBUNDLE EVENTS ONLY STOPPED")
for ev in bundle_stopped_set:
    if ev not in bundle_started_set:
        print(ev)

print("\n\n\nBUNDLE EVENTS not STARTED NOR STOPPED")
for ev in bundle_set:
    if ev not in bundle_stopped_set and ev not in bundle_started_set:
        print(ev) """



Total_Bundles_list=[
"System Bundle",
"Abdera Client",
"Abdera Core",
"Abdera Extensions - Media",
"Abdera Extensions - OpenSearch",
"Abdera Server",
"Adaptive Forms Core API",
"Adaptive Forms Core Implementation",
"Adobe - XMPFiles Worker host",
"Adobe - XMPFiles Worker platform fragment linux",
"Adobe - XMPFiles Worker platform fragment macosx",
"Adobe - XMPFiles Worker platform fragment win",
"Adobe :: SuiteTech :: Nativecomm",
"Adobe AEM - SEO",
"Adobe AEM - SEO Implementation",
"Adobe AEM - WCM Asynchronous Jobs support",
"Adobe AEM Configuration Updater",
"Adobe AEM Deserialization Firewall",
"Adobe AEM Script Injector",
"Adobe Brand Portal Cloudservice configuration",
"Adobe Communique 5 Commerce Core",
"Adobe Communique 5 Commerce Product Information Manager",
"Adobe Communique 5 Commerce Social",
"Adobe Communique 5 Dashboards",
"Adobe Communique 5 History",
"Adobe Communique 5 Launches API",
"Adobe Communique 5 Scheduled Exporter",
"Adobe Communique 5 Upgrades Executor",
"Adobe Communique 5 WCM Launches Core",
"Adobe CQ - DTM Integration Bundle",
"Adobe CQ Account Management",
"Adobe CQ Activation DTM Core Bundle",
"Adobe CQ Activation DTM UI Bundle",
"Adobe CQ Address",
"Adobe CQ Cloud Config Components Bundle",
"Adobe CQ Cloud Config Core Bundle",
"Adobe CQ Cloud Config UI Bundle",
"Adobe CQ Content Insight and Recommendations",
"Adobe CQ ContextHub Commons",
"Adobe CQ Creative Cloud APIs - DAM SVG Asset Handler",
"Adobe CQ DAM - Adobe Marketing Cloud Synchronisation Bundle",
"Adobe CQ DAM - Adobe Marketing Cloud Synchronisation Helper",
"Adobe CQ DAM - Index Builder",
"Adobe CQ DAM annotation print implementation",
"Adobe CQ DAM Delivery API",
"Adobe CQ DAM Delivery Internal API",
"Adobe CQ DAM Entitlement Implementation",
"Adobe CQ DAM Scene7 Dynamic Imaging",
"Adobe CQ DAM Stock Integration",
"Adobe CQ Experience Log Client Bundle",
"Adobe CQ Graphics Rendering API",
"Adobe CQ JSON Exporter",
"Adobe CQ JSON Exporter Implementation",
"Adobe CQ Nui API",
"Adobe CQ Nui Bundle",
"Adobe CQ Remote DAM API Bundle",
"Adobe CQ Remote Dam Client Core Bundle",
"Adobe CQ Remote DAM Commons Bundle",
"Adobe CQ Remote DAM Server Core",
"Adobe CQ REST API Sites",
"Adobe CQ Search Extension",
"Adobe CQ Search QueryBuilder",
"Adobe CQ Search Suggestions",
"Adobe CQ Security Health Checks",
"Adobe CQ Translation Workflow",
"Adobe CQ WCM Foundation Components",
"Adobe CQ WCM Scripting Support",
"Adobe DAM InDesign Print",
"Adobe DAM WebDAV Support",
"Adobe Experience Manager Command Implementation",
"Adobe Experience Manager Core WCM Components Core Bundle",
"Adobe Experience Manager Core WCM Components Extension - Structured Content Fragment Bundle",
"Adobe Experience Manager GraphQL for Content Fragments",
"Adobe Experience Manager GraphQL for Sites - API",
"Adobe Experience Manager GraphQL for Sites - Base Module",
"Adobe Experience Manager GraphQL Java Wrapper",
"Adobe Experience Manager GraphQL Sling Adapter",
"Adobe Experience Manager HTL Extension",
"Adobe FO Markup Layout Library",
"Adobe Font Engine",
"Adobe FormsPortal Services Bundle",
"Adobe GLobalization Library(Min)",
"Adobe Granite - SAML 2.0 Authentication Handler",
"Adobe Granite ACP Platform",
"Adobe Granite Activity Streams",
"Adobe Granite API Controller",
"Adobe Granite Asset API",
"Adobe Granite Asset API Implementation",
"Adobe Granite Async Jobs",
"Adobe Granite Async Jobs",
"Adobe Granite Authentication Handler",
"Adobe Granite Certificate Authentication Handler",
"Adobe Granite Cloud Settings Core Bundle",
"Adobe Granite Commenting Support",
"Adobe Granite Commons Library - JavaServer Pages Standard Tag Library",
"Adobe Granite Commons Library - JDBC pool provider for the Data Source Pool",
"Adobe Granite Compat Router",
"Adobe Granite Conf Manager",
"Adobe Granite Configuration Manager UI Core Module",
"Adobe Granite Context-Aware Configuration Extension",
"Adobe Granite ContextHub Commons",
"Adobe Granite CORS Support",
"Adobe Granite CRX Explorer",
"Adobe Granite CRX Package Manager",
"Adobe Granite CRXDE Lite",
"Adobe Granite Crypto Bundle Key Provider",
"Adobe Granite Crypto Configuraton",
"Adobe Granite Crypto Extension",
"Adobe Granite Crypto JCR Key Provider",
"Adobe Granite Crypto Keystore",
"Adobe Granite Crypto Support",
"Adobe Granite CSRF Framework",
"Adobe Granite Frags",
"Adobe Granite Health Checks for the Repository",
"Adobe Granite Health Checks related to bundles",
"Adobe Granite Health Checks related to Replication",
"Adobe Granite HTTP Cache - Core Bundle",
"Adobe Granite I18N Module",
"Adobe Granite IMSAuthentication Handler",
"Adobe Granite Installer for Content Packages",
"Adobe Granite JCR Cluster Support",
"Adobe Granite JMX Support",
"Adobe Granite License Module",
"Adobe Granite Maintenance Core",
"Adobe Granite Monitoring Support",
"Adobe Granite OAuth Authentication Handler",
"Adobe Granite OAuth Server",
"Adobe Granite Offloading Core",
"Adobe Granite Offloading Workflow",
"Adobe Granite Omnisearch Core Module",
"Adobe Granite Operations Dashboard UI Core Package",
"Adobe Granite Opt-Out Module",
"Adobe Granite org.json-20231013 Wrapper",
"Adobe Granite References Core Bundle",
"Adobe Granite Replication",
"Adobe Granite Repository Check bundle",
"Adobe Granite Resource Status Bundle",
"Adobe Granite ResourceResolver Helper",
"Adobe Granite RESTful API Assets",
"Adobe Granite RESTful API Core",
"Adobe Granite Security Module",
"Adobe Granite Security Permissions Module",
"Adobe Granite Security UI Module",
"Adobe Granite Sling Distribution - Core",
"Adobe Granite Social Graph",
"Adobe Granite SocketIO - Core",
"Adobe Granite SSL ContextFactory for Jetty",
"Adobe Granite SSO Authentication Handler",
"Adobe Granite Startup Module",
"Adobe Granite Taskmanagement API",
"Adobe Granite Taskmanagement Core",
"Adobe Granite Taskmanagement Workflow Integration",
"Adobe Granite Thread Dumps collector",
"Adobe Granite Timeline Support",
"Adobe Granite Toggle API",
"Adobe Granite Toggle Frontend Servlet",
"Adobe Granite Toggle Static Connector",
"Adobe Granite Token Authentication",
"Adobe Granite UI Clientlibs",
"Adobe Granite UI Clientlibs - Google Closure Compiler",
"Adobe Granite UI Clientlibs - Less Compiler",
"Adobe Granite UI Commons",
"Adobe Granite UI Tags",
"Adobe Granite UI Widgets",
"Adobe Granite Workflow API",
"Adobe Granite Workflow Console",
"Adobe Granite Workflow Core",
"Adobe Granite XSS Protection",
"Adobe IMS Core Bundle",
"Adobe PDF Core",
"Adobe PDF Encryption",
"Adobe PDF Extraction services",
"Adobe PDF Java Toolkit",
"Adobe PDF Manipulation services",
"Adobe PDF Security services",
"Adobe Reef Siren",
"Adobe Rideau(I/O)",
"Adobe Screens JMS implementation",
"Adobe Stock Apis SDK",
"Adobe XMP Core Duo",
"Adobe XMP RNG Parser",
"Adobe XMP Schema Model",
"Adobe XMP Schema Service",
"Adobe XMPCore",
"AEM - DAM Sling Model Bundle",
"AEM - Experience Fragments",
"AEM - Experience Fragments Social",
"AEM - Inbox API",
"AEM - Inbox Core",
"AEM - Inbox UI",
"AEM - Reference Update Processor API bundle",
"AEM - Reference Update Processor Impl bundle",
"AEM - Reference Update Processor Utility bundle",
"AEM - Social Media Integration",
"AEM 6 - Adobe Search&Promote Integration",
"AEM 6 - Adobe Target integration",
"AEM 6 - Adobe Target Recommendations Integration",
"AEM 6 - MSM Support for Adobe Target integration",
"AEM 6 ActivityMap Integration Bundle",
"AEM 6 Analytics Integration Bundle",
"AEM API metrics agent",
"AEM API metrics agent add-on for registry-based vault package analysis",
"AEM Cloud Services - Provisioning Bundle",
"AEM Communities ActivityStreams - Bundle",
"AEM Communities AdobeSocial Resource Provider - Bundle",
"AEM Communities Badging - Bundle",
"AEM Communities Badging API - Bundle",
"AEM Communities Basic Badging - Bundle",
"AEM Communities Calendar - API Bundle",
"AEM Communities Calendar - Impl Bundle",
"AEM Communities Commons - Bundle",
"AEM Communities Commons Oauth - Bundle",
"AEM Communities CommunityGroup - Bundle",
"AEM Communities Console - Bundle",
"AEM Communities Content Fragments Impl - Bundle",
"AEM Communities Enablement Api - Bundle",
"AEM Communities Enablement Impl - Bundle",
"AEM Communities Enablement Reporting Management- Bundle",
"AEM Communities File Library - Bundle",
"AEM Communities Forum - Bundle",
"AEM Communities Gamification API - Bundle",
"AEM Communities Gamification Impl - Bundle",
"AEM Communities Handlebars Scripting Engine - Bundle",
"AEM Communities Ideation - Bundle",
"AEM Communities Ideation API - Bundle",
"AEM Communities JCR Resource Provider (6.2+ glue) - Bundle",
"AEM Communities JCR Resource Provider Common Code - Bundle",
"AEM Communities Journal - Bundle",
"AEM Communities Members API - Bundle",
"AEM Communities Members Impl - Bundle",
"AEM Communities Messaging - API Bundle",
"AEM Communities Messaging - Impl Bundle",
"AEM Communities Moderation - Bundle",
"AEM Communities Mongo Storage Resource Provider - Bundle",
"AEM Communities Notifications - API Bundle",
"AEM Communities Notifications - IMPL Bundle",
"AEM Communities Notifications - Web Channel",
"AEM Communities QnA - Bundle",
"AEM Communities Relational Social Resource Provider - Bundle",
"AEM Communities Review - Bundle",
"AEM Communities SCF - API Bundle",
"AEM Communities SCF - Impl Bundle",
"AEM Communities Scoring - Bundle",
"AEM Communities Scoring API - Bundle",
"AEM Communities Scoring Basic - Bundle",
"AEM Communities Service Users - Bundle",
"AEM Communities Service Users - Impl Bundle",
"AEM Communities SocialGraph API - Bundle",
"AEM Communities SocialGraph Impl - Bundle",
"AEM Communities Spam Detection Core - Bundle",
"AEM Communities SRP - Impl Bundle",
"AEM Communities SRP Base - API Bundle",
"AEM Communities Sync - Bundle",
"AEM Communities Tally - Bundle",
"AEM Communities Translation - Bundle",
"AEM Communities UGC Base - API Bundle",
"AEM Communities UGC Base - Impl Bundle",
"AEM Communities UGC SearchCollections - Bundle",
"AEM Communities User Ugc Moderation - Bundle",
"AEM Dynamic Media Integration",
"AEM Dynamic Media Integration API",
"AEM Forms and Documents Core",
"AEM Forms Transaction Core Bundle",
"AEM MSM - UI Utilities",
"AEM Personalization",
"AEM Pre-Upgrade Maintenance Tasks",
"AEM Screens - Core",
"AEM Screens - Core (Session Support)",
"AEM Screens - DCC",
"AEM Sites - UI Utilities",
"AEM UI WCM Admin Bundle",
"AEM UI WCM Commons Bundle",
"AEM UI WCM Editor Bundle",
"AEM WCM - Models Extension",
"AEM WCM Components - UI Utilities",
"AEM WCM Style API",
"AEM WCM Utility to manage hierarchies",
"ANTLR 4 Runtime",
"Apache Apache HttpClient OSGi bundle (Adobe vendor branch)",
"Apache Apache HttpCore OSGi bundle",
"Apache Aries JMX API",
"Apache Aries JMX Core",
"Apache Aries Transaction Manager",
"Apache Aries Util",
"Apache Aries Whiteboard support for JMX DynamicMBean services",
"Apache Cocoon XML Utilities",
"Apache Commons Codec",
"Apache Commons Collections",
"Apache Commons Collections",
"Apache Commons Compress",
"Apache Commons Email",
"Apache Commons Exec",
"Apache Commons FileUpload",
"Apache Commons Imaging",
"Apache Commons IO",
"Apache Commons Lang",
"Apache Commons Text",
"Apache Felix - System Ready",
"Apache Felix Configuration Admin Service",
"Apache Felix Coordinator Service",
"Apache Felix Declarative Services",
"Apache Felix EventAdmin",
"Apache Felix Http Jetty",
"Apache Felix Http SSL Filter",
"Apache Felix Http Whiteboard",
"Apache Felix Inventory",
"Apache Felix JAAS Support",
"Apache Felix Metatype Service",
"Apache Felix Servlet API",
"Apache Felix Thread Dump",
"Apache Felix Web Console Event Plugin",
"Apache Felix Web Console Memory Usage Plugin",
"Apache Felix Web Console Package Admin Service Plugin",
"Apache Felix Web Console Service Component Runtime/Declarative Services Plugin",
"Apache Felix Web Management Console",
"Apache FOP bundle",
"Apache Geronimo Annotation Spec 1.3",
"Apache Geronimo JSR-330 Spec API",
"Apache Jackrabbit API",
"Apache Jackrabbit FileVault Core Bundle",
"Apache Log4j API",
"Apache Log4j to SLF4J Adapter",
"Apache Oltu - Commons - Encoded Token",
"Apache Oltu - JOSE - JWS",
"Apache Oltu - OAuth 2.0 - Common",
"Apache Oltu - OAuth 2.0 - JWT",
"Apache OpenNLP Tools",
"Apache ServiceMix :: Bundles :: abdera-parser",
"Apache ServiceMix :: Bundles :: dom4j",
"Apache ServiceMix :: Bundles :: jaxb-runtime",
"Apache ServiceMix :: Bundles :: jdom",
"Apache ServiceMix :: Bundles :: rhino",
"Apache ServiceMix :: Bundles :: saaj-impl",
"Apache ServiceMix :: Specs :: JAXB API 2.3",
"Apache ServiceMix :: Specs :: JAXWS API 2.2",
"Apache ServiceMix :: Specs :: SAAJ API 1.3",
"Apache Sling Adapter Manager Implementation",
"Apache Sling API",
"Apache Sling API Compatibility Bundle",
"Apache Sling Atom Tag Library",
"Apache Sling Auth Core",
"Apache Sling Bundle Resource Provider",
"Apache Sling Commons Compiler",
"Apache Sling Commons FileSystem ClassLoader",
"Apache Sling Commons HTML Utilities",
"Apache Sling Commons Johnzon Wrapper Library",
"Apache Sling Commons Log",
"Apache Sling Commons Metrics RRD4J",
"Apache Sling Commons MIME",
"Apache Sling Commons OSGi support",
"Apache Sling Commons Scheduler Support",
"Apache Sling Content Detection Support",
"Apache Sling Context-Aware Configuration API",
"Apache Sling Context-Aware Configuration Implementation",
"Apache Sling Context-Aware Configuration SPI",
"Apache Sling DataSource Provider",
"Apache Sling Default GET Servlets (Adobe Vendor Branch)",
"Apache Sling Default POST Servlets",
"Apache Sling Discovery API",
"Apache Sling Discovery Base",
"Apache Sling Discovery Commons",
"Apache Sling Discovery Support Bundle",
"Apache Sling Distributed Event Admin",
"Apache Sling Distribution API",
"Apache Sling Distribution Core (Adobe Vendor Branch)",
"Apache Sling Dynamic Class Loader Support",
"Apache Sling Engine",
"Apache Sling Event Support",
"Apache Sling Feature Flags",
"Apache Sling File Installer",
"Apache Sling Health Check API",
"Apache Sling Health Check Core",
"Apache Sling Health Check Webconsole Plugin",
"Apache Sling Hypermedia API tools",
"Apache Sling I18N Support",
"Apache Sling Initial Content Loader",
"Apache Sling Installer (Adobe Vendor Branch)",
"Apache Sling Installer Configuration Factory",
"Apache Sling Installer WebConsole Plugin",
"Apache Sling Inventory Printer Based on Resources",
"Apache Sling javax.activation bundle",
"Apache Sling JCR Base",
"Apache Sling JCR DavEx",
"Apache Sling JCR Installer",
"Apache Sling JCR Repository Registration",
"Apache Sling JCR Resource Resolver",
"Apache Sling JCR Resource Security",
"Apache Sling JMX Resource Provider",
"Apache Sling JSON Library",
"Apache Sling Launchpad Installer",
"Apache Sling Log Tracer",
"Apache Sling Log WebConsole",
"Apache Sling Metrics",
"Apache Sling Models API",
"Apache Sling Models Implementation (Adobe Vendor Branch)",
"Apache Sling Models Model Exporter - Jackson",
"Apache Sling Oak-Based Discovery Service",
"Apache Sling OSGi LogService Implementation",
"Apache Sling Provisioning Model",
"Apache Sling Repoinit JCR",
"Apache Sling Repoinit Parser",
"Apache Sling Repository API Bundle",
"Apache Sling Resource Access Security",
"Apache Sling Resource Collection API",
"Apache Sling Resource Merger",
"Apache Sling Resource Resolver",
"Apache Sling Rewriter",
"Apache Sling Scripting Core",
"Apache Sling Scripting EL API Wrapper",
"Apache Sling Scripting HTL Compiler",
"Apache Sling Scripting HTL Engine",
"Apache Sling Scripting HTL Java Compiler",
"Apache Sling Scripting HTL JS Use Provider",
"Apache Sling Scripting HTL Runtime",
"Apache Sling Scripting Implementation API",
"Apache Sling Scripting Java",
"Apache Sling Scripting JavaScript",
"Apache Sling Scripting JSP",
"Apache Sling Scripting JSP Tag Library",
"Apache Sling Scripting SPI",
"Apache Sling Security",
"Apache Sling Service User Mapper",
"Apache Sling Servlets Resolver",
"Apache Sling Settings",
"Apache Sling Simple WebDAV Access to repositories",
"Apache Sling Sitemap",
"Apache Sling Startup Filter",
"Apache Sling Startup Filter Disabler",
"Apache Sling Tenant",
"Apache Sling Thread Support",
"Apache Sling Web Console Security Provider",
"Apache Sling Wrapper Bundle for Apache Tomcat JSP API",
"Apache Sling Wrapper Bundle for the JCR API",
"Apache Sling XSS Protection API",
"Apache Tika core",
"Apache Tika parsers",
"CDN Integration Bundle",
"chiranjib Project - Core",
"Commons Lang",
"Commons Math",
"ContentFragmentManagement - API",
"ContentFragmentManagement - Extensions",
"ContentFragmentManagement - HTTP API",
"ContentFragmentManagement - Implementation",
"CQ Health Check Services",
"CQ Pre-upgrade Backup",
"CQ Pre-upgrade Cleanup",
"CQ ProductInfo Provider",
"CQ Projects - API Bundle",
"CQ Projects - Core Bundle",
"CQ Projects - UI Bundle",
"DAM Similarity Search Bundle",
"Day Commons Library - Data Source Pool",
"Day Commons Library - Diff (Diff utilities)",
"Day Commons Library - Durbo Content Packaging",
"Day Commons Library - Graphics Support Library (gfx)",
"Day Commons Library - HTTP Client 3.1 Bundling",
"Day Commons Library - Input/Output Support",
"Day Commons Library - jrawio bundling",
"Day Commons Library - Miscellaneous Functions",
"Day Commons Library - Simple JNDI",
"Day Commons Library - Text Support",
"Day Communique 5 Adobe Campaign Integration",
"Day Communique 5 Assets Rating",
"Day Communique 5 Audit Bundle",
"Day Communique 5 Charting",
"Day Communique 5 Code Upgrade service",
"Day Communique 5 Commons Library",
"Day Communique 5 Compatiblity: Apache Sling Commons Auth Interim API",
"Day Communique 5 Compatiblity: Apache Sling Runmode",
"Day Communique 5 Content Sync",
"Day Communique 5 DAM Adobe extension",
"Day Communique 5 DAM API",
"Day Communique 5 DAM Asset Handler Implementation",
"Day Communique 5 DAM Commons",
"Day Communique 5 DAM Core Implementation",
"Day Communique 5 DAM InDesign Integration",
"Day Communique 5 DAM PIM Integration Implementation",
"Day Communique 5 DAM Scene7 API Wrapper Bundle",
"Day Communique 5 DAM Scene7 Integration",
"Day Communique 5 DAM Scene7 Integration",
"Day Communique 5 DAM Video Extensions",
"Day Communique 5 DAM Word Integration",
"Day Communique 5 Ext Widgets",
"Day Communique 5 JCR Connector Integration",
"Day Communique 5 License Branding",
"Day Communique 5 Mailer",
"Day Communique 5 MCM Core Implementation",
"Day Communique 5 MCM External Email Provider Interface",
"Day Communique 5 MCM Landing Page Implementation",
"Day Communique 5 Media Articles Implementation",
"Day Communique 5 Notification API",
"Day Communique 5 Notification Implementation",
"Day Communique 5 Polling Importer",
"Day Communique 5 Replication - Auditing",
"Day Communique 5 Reporting",
"Day Communique 5 Retriever",
"Day Communique 5 Rewriter",
"Day Communique 5 Security",
"Day Communique 5 Security API",
"Day Communique 5 Spellchecker",
"Day Communique 5 Statistics",
"Day Communique 5 Tagging",
"Day Communique 5 WCM API",
"Day Communique 5 WCM Commons",
"Day Communique 5 WCM Content Sync Extensions",
"Day Communique 5 WCM Core Implementation",
"Day Communique 5 WCM Design Importer",
"Day Communique 5 WCM Emulator",
"Day Communique 5 WCM Mobile API",
"Day Communique 5 WCM Mobile Core",
"Day Communique 5 WCM Multi Site Management API",
"Day Communique 5 WCM Multi Site Management Commons",
"Day Communique 5 WCM Multi Site Management Core",
"Day Communique 5 WCM Multi Site Management Move Handle API",
"Day Communique 5 WCM NodeNameIndexer Implementation",
"Day Communique 5 WCM Notification Bundle",
"Day Communique 5 WCM Offline Editor",
"Day Communique 5 WCM Site Importer",
"Day Communique 5 WCM Tag Lib",
"Day Communique 5 WCM Undo",
"Day Communique 5 WCM Webservice Support",
"Day Communique 5 WCM Workflow",
"Day Communique 5 WCM Workflow API",
"Day Communique 5 Workflow API",
"Day Communique 5 Workflow Console",
"Day Communique 5 Workflow Implementation",
"Day Communique 6 DAM Asset Sourcing Implementation",
"Day Communique 6.0 DAM Asset Usage Implementation",
"Day Communique WCM Resource Details",
"Day CRX API",
"Ehcache 3",
"Expression Editor Utils Bundle",
"Extended StAX API",
"Forms Foundation Base Bundle",
"Forms Foundation Cloud Configurations Bundle",
"Forms Foundation Layer Bundle",
"Granite Info Collector",
"Granite Logging - Analysis",
"Granite Maintenance OAK",
"Granite OAuth JWT",
"Granite Queries",
"Granite Requests Logging",
"Granite Translation - Microsoft Connector Core Bundle",
"Granite Translation - Translation API",
"Granite Translation - Translation Core",
"Granite Webconsole Plugins",
"GraphiQL :: Core",
"GraphQL - API",
"GraphQL - Impl",
"Gson",
"Guava Wrapper bundle",
"H2 MVStore",
"Handlebars",
"I18N Libraries",
"Jackrabbit API",
"Jackrabbit Data",
"Jackrabbit JCR Commons",
"Jackrabbit SPI",
"Jackrabbit SPI Commons",
"Jackrabbit WebDAV Library",
"Jackson-annotations",
"Jackson-core",
"jackson-databind",
"Java Encoder",
"JavaMail API",
"jcl-over-slf4j",
"Joda-Time",
"JSON Schema Parser Bundle",
"json-io",
"JSON-P Default Provider",
"JSPEL Expression Resolver Bundle",
"log4j-over-slf4j",
"MarkdownJ Wrapper bundle",
"Metrics Core",
"Mobile Forms Common Bundle",
"Mobile QR Code Generator",
"mongo-java-driver",
"Multi Channel Core",
"MySpell",
"Oak API",
"Oak Azure Cloud Blob Store",
"Oak Blob Plugins",
"Oak Blob Store",
"Oak Commons",
"Oak Composite Store",
"Oak content repository",
"Oak Core",
"Oak Core SPI",
"Oak CUG Authorization",
"Oak DocumentNodeStore",
"Oak External Authentication Support",
"Oak JCR Binding",
"Oak LDAP Authentication Support",
"Oak Lucene",
"Oak NodeStore and Commit SPI",
"Oak Query SPI",
"Oak Security SPI",
"Oak Segment Azure",
"Oak Segment Tar",
"Oak Solr OSGi",
"org.apache.oltu.commons.json",
"org.apache.oltu.oauth2.authzserver",
"org.apache.oltu.oauth2.client",
"org.apache.oltu.oauth2.resourceserver",
"org.osgi:org.osgi.util.converter",
"org.osgi:org.osgi.util.function",
"org.osgi:org.osgi.util.promise",
"OSGi bundle wrapper for the Apache POI library",
"OSGi bundle wrapper for the Scribe library",
"OSGi bundle wrapper for the Tagsoup library",
"RELAX NG Object Model / Parser",
"Remote Content Renderer",
"Screens WeRetail",
"slf4j-api",
"SmartContent - Core Implementation",
"WCM Projects - Core Bundle",
"We.Retail - Core",
"Web Services Metadata 2.0",
"xtg"
]

c=0
for x in Total_Bundles_list:
    if x not in bundle_set:
        print(x)
        c+=1

print(c)